[project]
name = "github-trending-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yange", email = "posterscofield@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
ghtrend = "github_trending_cli.__main__:main"

